"""up

Revision ID: a328bf58c5c3
Revises: 
Create Date: 2017-08-20 12:37:08.616000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a328bf58c5c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_train',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('describe', sa.String(length=128), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('able', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tb_train_file_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_train_file_type_file_type'), 'tb_train_file_type', ['file_type'], unique=True)
    op.create_table('tb_train_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=2), nullable=False),
    sa.Column('leader', sa.String(length=32), nullable=True),
    sa.Column('members', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('train_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['train_id'], ['tb_train.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_train_team_number'), 'tb_train_team', ['number'], unique=False)
    op.create_table('tb_train_files ',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('path', sa.String(length=128), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('able', sa.Boolean(), nullable=True),
    sa.Column('train_id', sa.Integer(), nullable=True),
    sa.Column('train_team_id', sa.Integer(), nullable=True),
    sa.Column('train_file_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['train_file_type_id'], ['tb_train_file_type.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['tb_train.id'], ),
    sa.ForeignKeyConstraint(['train_team_id'], ['tb_train_team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'tb_users', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column(u'tb_users', sa.Column('train_team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tb_users', 'tb_train_team', ['train_team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_users', type_='foreignkey')
    op.drop_column(u'tb_users', 'train_team_id')
    op.drop_column(u'tb_users', 'create_time')
    op.drop_table('tb_train_files ')
    op.drop_index(op.f('ix_tb_train_team_number'), table_name='tb_train_team')
    op.drop_table('tb_train_team')
    op.drop_index(op.f('ix_tb_train_file_type_file_type'), table_name='tb_train_file_type')
    op.drop_table('tb_train_file_type')
    op.drop_table('tb_train')
    # ### end Alembic commands ###
